#!/usr/bin/env bash

PROJECT_ROOT=$(stack path --project-root)

if [ -z "$PROJECT_ROOT" ]; then
    exit 1
fi

cat "$PROJECT_ROOT/stack.yaml" "$PROJECT_ROOT/ghcjs.yaml" > "$PROJECT_ROOT/stack.ghcjs.yaml"

stack --stack-yaml "$PROJECT_ROOT/stack.ghcjs.yaml" "$@"